plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

title: Karol Piątek Blog
  
# Site Author
author:
  name             : "Karol Piątek"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I'm Senior iOS developer with over 4 years of experience in iOS development. I'm highly interested in mobile security and constantly working on those skills."
  location         : "Remote"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/karolpiatek/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/karolpiateknet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karolpiateknet"
