remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

title                    : "Swifty Friday Blog"
title_separator          : "-"
name                     : "Karol Piątek"
description              : "iOS development, mobile security, development cycle"

search                   : true
lunr:
  search_within_pages    : true

# Social Sharing
twitter:
  username               : "karolpiateknet"

# Site Author
author:
  name             : "Karol Piątek"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I'm Senior iOS developer with over 4 years of experience in iOS development. I'm highly interested in mobile security and constantly working on those skills."
  location         : "Remote"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/karolpiatek/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/karolpiateknet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karolpiateknet"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/karolpiatek/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/karolpiateknet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karolpiateknet"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
