remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

title                    : "Swifty Friday Blog"
title_separator          : "-"
name                     : "Karol Piątek"
description              : "iOS development, mobile security, development cycle"
author_profile           : true
timezone: "Poland"
breadcrumbs: true

search                   : true
lunr:
  search_within_pages    : true

# Social Sharing
twitter:
  username               : "karolpiateknet"

# Site Author
author: Karol Piatek

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/karolpiatek/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/karolpiateknet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karolpiateknet"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: "/_posts/"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
