remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

# Site Settings
locale                   : "en-US"
title                    : "Swifty Friday Blog"
title_separator          : "-"
subtitle                 : "iOS development, mobile security, development cycle"
name                     : "Karol Piątek"
description              : "Senior iOS developer with interests in mobile security"
author_profile           : true
timezone: "Poland"
breadcrumbs: true

search                   : true
lunr:
  search_within_pages    : true

# Social Sharing
twitter:
  username               : "karolpiateknet"

# Site Author
author: Karol Piatek

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/karolpiatek/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/karolpiateknet"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karolpiateknet"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-analytics
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: "about"
      type: pages
    values:
      layout: single
      author_profile: true
